<h1>overmij | Baran Kocaoz</h1>
                        <table>
                            <tr>
                                <th>Foto</th>
                                        <td><a href="portret.html" target=_blank><img src="images/209725.jpg" width="150" ></a></td>
                            </tr>
                            <tr>
                                <th>Naam</th>
                                    <td>
                                        <UL>
                                            <li>Baran Kocaöz</li>
                                        </UL>
                                    </td>
                            </tr>
                            <tr>
                                <th>Klas</th>
                                    <td>
                                        <UL>
                                            <li>4 HAVO</li>
                                        </UL>
                                    </td>
                            </tr>
                            <tr>
                                <th>Hobby's</th>
                                    <td>
                                        <ul>
                                            <li>Gamen, ik game vaak meteen na school en wil zo lang mogelijk doorgaan met gamen</li>
                                            <li>Jasper pesten</li>
                                        </ul>
                                    </td>
                            </tr>
                            <tr>
                                <th>Richting na de middelabre school</th>
                                    <td>
                                        <ul>
                                            <li>Ik wil na de middelabre school eerst VWO wiskunde doen, daarna 1 jaar HBO, daarna een vliegers opleiding bij Defensie.</li>
                                        </ul>
                                    </td>
                            </tr>
                            <tr>
                                <th>Wat weet je al over informatica?</th>
                                    <td>
                                        <UL>
                                            <li>Python</li> 
                                            <li>schakelingen</li>
                                        </UL>
                                    </td>
                            </tr>
                            <tr>
                                <th>Wat wil je nog leren bij informatica?</th>
                                    <td>
                                        <UL>
                                            <li>JavaScript</li> 
                                            <li>Game design</li>
                                        </UL>
                                    </td>
                            </tr>
                            <tr>
                                <th>Lievelings kleur</th>
                                    <td>
                                        <ul>
                                            <li>
                                                Rood
                                            </li>
                                        </ul>
                                    </td>
                            </tr>
                            <tr>
                                <th>Lievelings artiesten</th>
                                    <td>
                                        <ul>
                                            <li>Rick Ashley</li>
                                            <li>Fumez The Engineer</li>
                                        </ul>
                                    </td>
                            </tr>
                            <tr>
                                <th>Lievelings bands</th>
                                    <td>
                                        <ul>
                                            <li>Bankzitters</li>
                                            <li>The Beatles</li>
                                            <li>Queen</li>
                                        </ul>
                                    </td>
                            </tr>
                            <tr>
                                <th>Lievelings getal</th>
                                    <td>
                                        <ul>
                                            <li>
                                                9
                                            </li>
                                        </ul>
                                    </td>
                            </tr>
                            <tr>
                                <th>Lievelings nummers</th>
                                    <td>
                                        <ul>
                                            <li><a href="https://youtu.be/dQw4w9WgXcQ" target=_blank> Never gonna give you up</a></li>
                                            <li><a href="https://www.youtube.com/watch?v=cPJUBQd-PNM" target=_blank> "Revenge" minecraft parody</a></li>
                                            <li><a href="https://youtu.be/I2YFJ2b_WEQ" target="_blank">Plugged in</a></li>
                                        </ul>
                                    </td>
                            </tr>
                            <tr>
                                <th>Lievelings games</th>
                                    <td>
                                        <ul>
                                            <li> CS:GO</li>
                                            <li> Dead By Daylight</li>
                                        </ul>
                                    </td>
                            </tr>
                            <tr>
                                <th>Lievelings etens</th>
                                    <td>
                                        <ul>
                                            <li>Döner</li>
                                            <li>Pizza</li>
                                        </ul>
                                    </td>
                            </tr>
                            <tr>
                                <th>Lievelings atractie park</th>
                                    <td>
                                        <ul>
                                            <li>Toverland</li>
                                        </ul>
                                    </td>
                            </tr>
                            <tr>
                                <th>Lievelings atractie</th>
                                    <td>
                                        <ul>
                                            <li>Troy</li>
                                        </ul>
                                    </td>
                            </tr>
                        </table>