<div id="rekenmachine">
    <h2>De beste rekenmachine!</h2>
    <form name="form1">
        <input type="text" name="waarde1" value="1"><br>
        <input type="text" name="waarde2" value="2"><br>
        <input type="text" name="uitkomst" value=""><br>
        <input type="button" name="reset" value="Leeg vegen" onclick="LeegMaken()">
        <input type="button" name="optellen" value="+" onclick="OpTellen()">
        <input type="button" name="aftrekken" value="-" onclick="AfTrekken()">
        <input type="button" name="delen" value="/" onclick="Delen()">
        <input type="button" name="vermenigvuldigen" value="*" onclick="Vermenigvuldigen()">
    </form>
</div>